import time
import numpy as np
from app.services.preprocess import preprocess_image
from app.services.model_selector import run_inference
from app.services.gradcam import generate_gradcam

def analyze_image(image_path, image_id, source="mobile"):
    start_time = time.time()

    # Preprocess
    image_array = preprocess_image(image_path, source)

    # Inference
    result = run_inference(image_array, source)

    # Extract fields from the structured result
    prediction = result["prediction"]
    confidence_percent = result["confidence"]
    confidence_level = result["confidence_level"]
    explanation = result["explanation"]
    
    # Optional: pass through type and severity if you want
    cataract_type = result.get("cataract_type")
    severity = result.get("severity")
    
    # Grad-CAM
    generate_gradcam(image_path, image_id)

    elapsed_time = round(time.time() - start_time, 3)
    result_dict = {
        "prediction": prediction,
        "confidence": confidence_percent,
        "confidence_level": confidence_level,
        "image_id": image_id,
        "image_source": source,
        "cataract_type": cataract_type,
        "severity": severity,
        "explanation": explanation,
        "gradcam_url": f"/outputs/gradcam_{image_id}",
        "inference_time_sec": elapsed_time,
        "medical_disclaimer": (
            "This result is generated by an AI system and is not a medical diagnosis. "
            "Please consult an eye care professional for confirmation."
        )
    }

    # Ensure all numpy types are converted to native Python types for JSON serialization
    def sanitize(obj):
        if isinstance(obj, np.generic):
            return obj.item()
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        if isinstance(obj, dict):
            return {k: sanitize(v) for k, v in obj.items()}
        if isinstance(obj, list):
            return [sanitize(v) for v in obj]
        return obj

    return sanitize(result_dict)