import time
import numpy as np
from app.services.preprocess import preprocess_image
from app.services.model_selector import run_inference

def analyze_image(image_path, image_id, source="cbm"):
    start_time = time.time()

    # Preprocess
    image_array = preprocess_image(image_path, source)

    # Inference
    result = run_inference(image_array, source)

    # Support both legacy and current CBM response schemas.
    prediction = result.get("prediction")
    explanation = result.get("explanation")
    cataract_type = result.get("cataract_type")
    severity = result.get("overall_severity") or result.get("severity")

    if "confidence" in result:
        confidence_percent = result.get("confidence")
    else:
        # Fallback for current CBM schema: convert presence score [0,1] to percentage.
        presence_score = float(result.get("presence_score", 0.0))
        confidence_percent = round(presence_score * 100, 2)

    confidence_level = result.get("confidence_level")
    if confidence_level is None:
        if confidence_percent >= 80:
            confidence_level = "High"
        elif confidence_percent >= 60:
            confidence_level = "Medium"
        else:
            confidence_level = "Low"

    elapsed_time = round(time.time() - start_time, 3)
    result_dict = {
        "prediction": prediction,
        "confidence": confidence_percent,
        "confidence_level": confidence_level,
        "image_id": image_id,
        "image_source": source,
        "cataract_type": cataract_type,
        "severity": severity,
        "explanation": explanation,
        "concepts": result.get("concepts"),
        "concept_confidences": result.get("concept_confidences"),
        "visual_explanations": result.get("visual_explanations"),
        "gradcam_path": result.get("gradcam_path"),
        "gradcam_paths": result.get("gradcam_paths"),
        "gradcam_run_id": result.get("gradcam_run_id"),
        "gradcam_error": result.get("gradcam_error"),
        "inference_time_sec": elapsed_time,
        "medical_disclaimer": (
            "This result is generated by an AI system and is not a medical diagnosis. "
            "Please consult an eye care professional for confirmation."
        )
    }

    # Ensure all numpy types are converted to native Python types for JSON serialization
    def sanitize(obj):
        if isinstance(obj, np.generic):
            return obj.item()
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        if isinstance(obj, dict):
            return {k: sanitize(v) for k, v in obj.items()}
        if isinstance(obj, list):
            return [sanitize(v) for v in obj]
        return obj

    return sanitize(result_dict)