import time
import numpy as np
from app.services.preprocess import preprocess_image
from app.services.model_selector import run_inference


def analyze_image(image_path, image_id, source="cbm"):
    start_time = time.time()

    image_array = preprocess_image(image_path, source)
    result = run_inference(image_array, source)

    elapsed_time = round(time.time() - start_time, 3)

    result_dict = {
        "image_id": image_id,
        "image_source": source,

        "prediction": result.get("prediction"),
        "is_cataract": result.get("is_cataract"),
        "presence_score": result.get("presence_score"),
        "cataract_probability": result.get("cataract_probability"),
        "cataract_probability_percent": result.get("cataract_probability_percent"),
        "decision_confidence_percent": result.get("decision_confidence_percent"),
        "presence_margin": result.get("presence_margin"),

        "overall_score": result.get("overall_score"),
        "overall_severity_score": result.get("overall_severity_score"),
        "overall_severity": result.get("overall_severity"),
        "overall_severity_label": result.get("overall_severity_label"),

        "cataract_type": result.get("cataract_type"),
        "primary_cataract_type": result.get("primary_cataract_type"),
        "mixed_subtypes": result.get("mixed_subtypes"),

        "dominant_concept": result.get("dominant_concept"),
        "concepts": result.get("concepts"),
        "concept_confidences": result.get("concept_confidences"),

        "explanation": result.get("explanation"),
        "explanation_text": result.get("explanation_text"),
        "visual_explanations": result.get("visual_explanations"),

        "gradcam_path": result.get("gradcam_path"),
        "raw_heatmap_path": result.get("raw_heatmap_path"),
        "center_prior_gradcam_path": result.get("center_prior_gradcam_path"),
        "heuristic_overlay_path": result.get("heuristic_overlay_path"),

        "gradcam_paths": result.get("gradcam_paths"),
        "heatmap_paths": result.get("heatmap_paths"),
        "heuristic_overlay_paths": result.get("heuristic_overlay_paths"),

        "gradcam_run_id": result.get("gradcam_run_id"),
        "gradcam_error": result.get("gradcam_error"),

        "inference_time_sec": elapsed_time,
        "medical_disclaimer": (
            "This result is generated by an AI system and is not a medical diagnosis. "
            "Please consult an eye care professional for confirmation."
        ),
    }

    def sanitize(obj):
        if isinstance(obj, np.generic):
            return obj.item()
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        if isinstance(obj, dict):
            return {k: sanitize(v) for k, v in obj.items()}
        if isinstance(obj, list):
            return [sanitize(v) for v in obj]
        return obj

    return sanitize(result_dict)